name: CI

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/
          .pio
        key: ${{ runner.os }}-pio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Generate ESP Web Tools Files
      run: |
        python generate_esp_web_tools.py

    - name: Deploy to GitHub Pages
      if: ${{ github.event_name != 'pull_request' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web/
